{
  "name": "arvados_fuse",
  "version": "2.4.2",
  "error": "{\"type\": 5, \"message\": \"Failed to install: Command '['/tmp/pypi/arvados_fuse/bin/python3', '-m', 'pip', 'install', 'arvados_fuse']' returned non-zero exit status 1.\"}"
}